<?php

namespace Esprit\ProjetBiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ValidationImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidationImportRepository extends EntityRepository
{
}
